### PR TITLE
[Fix][MoRI] Add MoRI-IO connector support

### LINKED ISSUE #126: [Feature]: MoRIIOConnector support
### 🚀 The feature, motivation and pitch

Are there any plans to support routing instances using the MoRI-IO connector? As I understand it, the service registration and `kv_transfer_params` are differrent vs NIXL/P2PNCCL, and `WRITE` mode requires concurrrent dispatch of requests to the prefill and decode instances.

Thanks in advance!  

### Alternatives

_No response_

### Additional context

_No response_

### Before submitting a new issue...

- [x] Make sure you already searched for relevant issues, and asked the chatbot living at the bottom right corner of the [documentation page](https://docs.vllm.ai/en/latest/), which can answer lots of frequently asked questions.

### PR DESCRIPTION
**Pull request by simondanielsson**
## Purpose

Fixes #126 and https://github.com/vllm-project/vllm/issues/38692.

This PR adds 
- `--kv-connector moriio` type for running vllm-router with MoRI-IO KV connector
- compatibility with MoRI connector with vllm 0.18.0+. 
  - [This PR](https://github.com/vllm-project/vllm/pull/34907) introduces a `transfer_id` in the `kv_transfer_params` in the MoRI-IO connector and [toy proxy](https://github.com/vllm-project/vllm/blob/91eea72330ef507c839596afc59f37732b045820/examples/online_serving/disaggregated_serving/moriio_toy_proxy_server.py#L231) (this PR is part of vllm 0.18.0). This PR applies the same for update the vllm-router, and also adds the required `remote_dp_size` for performing remote handshakes inside the MoRI connector. This allows us to support the MoRI-IO KV connector in vllm-router.

**Important**: This does **not** interfere with any other connectors functionality.

### Basic usage

```
vllm-router \
    --vllm-pd-disaggregation \
    --kv-connector moriio \
    --vllm-discovery-address "0.0.0.0:${PROXY_PING_PORT}" \
    --port "${ROUTER_PORT}" \
    --host 0.0.0.0 \
```

### Dependencies

- Hard dependency: (vllm) to slightly update connector messages to align with the P2pNcclConnector: https://github.com/vllm-project/vllm/pull/39565
- Nice to have (can be merged whenever): (router) add streaming support in the service discovery path in order to run `vllm bench serve` with the vllm backend: #114 
Order of merging should be (1) the vllm PR  (2) this PR (3) the streaming PR

## Test Plan

This PR can be used in conjunction with [this vllm PR](https://github.com/vllm-project/vllm/pull/39565) to run vllm w/ MoRI-IO KV connector and vllm-router.

Reproducer scripts can be found in this temporary branch: https://github.com/mpashkovskii/vllm/pull/4

It includes 
1. Dockerfiles for building the branches from source (incl installation of Broadcom NIC drivers, etc.), 
3. Scripts for testing MoRI+vllm-router using the images built in point 1,  both in single-node (run_pd_demo.sh) and multi-node setups (run_pd_demo_2node.sh‎)

The tests include both basic smoke test (example request), vllm bench serve, and GSM8K using lm_eval (although the latter two require streaming support as added in the PR(s) mentioned above).

## Test Result

See https://github.com/vllm-project/vllm/pull/39565 for full performance and accuracy benchmarks. Below we show results from minimal smoke test reproducer.
# 2 node using DSR1

Basic smoke test (note random params):

```bash
$ IS_PREFILL=1 PREFILL_IP=10.21.9.47 DECODE_IP=10.21.9.29     ./examples/online_serving/disaggregated_serving/moriio_pd_demo/run_pd_demo_2node.sh



Containers will be shut down automatically when this script exits.
(Set KEEP_ALIVE=1 to leave them running.)

>>> Smoke test: sending a completion request through vllm-router...
2026-04-10 15:06:06  INFO vllm_router_rs::routers::http::vllm_pd_router: src/routers/http/vllm_pd_router.rs:1436: vLLM route_completion called, use_discovery=true
2026-04-10 15:06:06  INFO vllm_router_rs::routers::http::vllm_pd_router: src/routers/http/vllm_pd_router.rs:1443: Using service discovery mode, processing vLLM two-stage request
2026-04-10 15:06:06  INFO vllm_router_rs::policies::consistent_hash: src/policies/consistent_hash.rs:281: Updated consistent hash ring with 1 workers and 160 virtual nodes
2026-04-10 15:06:06  INFO vllm_router_rs::policies::consistent_hash: src/policies/consistent_hash.rs:593: CONSISTENT_HASH_DEBUG: Extracted hash key: request_hash:f9454da6e4bbbd0a
2026-04-10 15:06:06  INFO vllm_router_rs::policies::consistent_hash: src/policies/consistent_hash.rs:598: CONSISTENT_HASH_DEBUG: Hash key 'request_hash:f9454da6e4bbbd0a' mapped to worker: http://10.21.9.47:8100
2026-04-10 15:06:06  INFO vllm_router_rs::policies::consistent_hash: src/policies/consistent_hash.rs:647: Consistent hash routing: key='request_hash:f9454da6e4bbbd0a' -> worker='http://10.21.9.47:8100' (index=0)
2026-04-10 15:06:06  INFO vllm_router_rs::policies::consistent_hash: src/policies/consistent_hash.rs:281: Updated consistent hash ring with 1 workers and 160 virtual nodes
2026-04-10 15:06:06  INFO vllm_router_rs::policies::consistent_hash: src/policies/consistent_hash.rs:593: CONSISTENT_HASH_DEBUG: Extracted hash key: request_hash:f9454da6e4bbbd0a
2026-04-10 15:06:06  INFO vllm_router_rs::policies::consistent_hash: src/policies/consistent_hash.rs:598: CONSISTENT_HASH_DEBUG: Hash key 'request_hash:f9454da6e4bbbd0a' mapped to worker: http://10.21.9.29:8200
2026-04-10 15:06:06  INFO vllm_router_rs::policies::consistent_hash: src/policies/consistent_hash.rs:647: Consistent hash routing: key='request_hash:f9454da6e4bbbd0a' -> worker='http://10.21.9.29:8200' (index=0)
[aiter] pciChipId: 0x74a1, CU count: 304
[aiter] hipModuleLoad: /usr/local/lib/python3.12/dist-packages/aiter_meta/hsa//gfx942/fmha_v3_fwd/MI300/fwd_hd192x128_bf16_causal_rtna_group.co GetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE
[aiter] hipModuleGetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE Success
[aiter] pciChipId: 0x74a1, CU count: 304
[aiter] hipModuleLoad: /usr/local/lib/python3.12/dist-packages/aiter_meta/hsa//gfx942/fmha_v3_fwd/MI300/fwd_hd192x128_bf16_causal_rtna_group.co GetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE
[aiter] pciChipId: 0x74a1, CU count: 304
[aiter] hipModuleLoad: /usr/local/lib/python3.12/dist-packages/aiter_meta/hsa//gfx942/fmha_v3_fwd/MI300/fwd_hd192x128_bf16_causal_rtna_group.co GetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE
[aiter] pciChipId: 0x74a1, CU count: 304
[aiter] hipModuleLoad: /usr/local/lib/python3.12/dist-packages/aiter_meta/hsa//gfx942/fmha_v3_fwd/MI300/fwd_hd192x128_bf16_causal_rtna_group.co GetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE
[aiter] hipModuleGetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE Success
[aiter] hipModuleGetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE Success
[aiter] hipModuleGetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE Success
[aiter] pciChipId: 0x74a1, CU count: 304
[aiter] hipModuleLoad: /usr/local/lib/python3.12/dist-packages/aiter_meta/hsa//gfx942/fmha_v3_fwd/MI300/fwd_hd192x128_bf16_causal_rtna_group.co GetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE
[aiter] pciChipId: 0x74a1, CU count: 304
[aiter] hipModuleLoad: /usr/local/lib/python3.12/dist-packages/aiter_meta/hsa//gfx942/fmha_v3_fwd/MI300/fwd_hd192x128_bf16_causal_rtna_group.co GetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE
[aiter] hipModuleGetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE Success
[aiter] pciChipId: 0x74a1, CU count: 304
[aiter] hipModuleLoad: /usr/local/lib/python3.12/dist-packages/aiter_meta/hsa//gfx942/fmha_v3_fwd/MI300/fwd_hd192x128_bf16_causal_rtna_group.co GetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE
[aiter] hipModuleGetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE Success
[aiter] hipModuleGetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE Success
[aiter] pciChipId: 0x74a1, CU count: 304
[aiter] hipModuleLoad: /usr/local/lib/python3.12/dist-packages/aiter_meta/hsa//gfx942/fmha_v3_fwd/MI300/fwd_hd192x128_bf16_causal_rtna_group.co GetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE
[aiter] hipModuleGetFunction: _ZN5aiter41fmha_fwd_hd192x128_bf16_causal_rtna_groupE Success
(APIServer pid=7) INFO:     10.21.9.47:58400 - "POST /v1/completions HTTP/1.1" 200 OK
(APIServer pid=7) INFO 04-10 15:07:08 [loggers.py:259] Engine 000: Avg prompt throughput: 0.5 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 0 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.0%, Prefix cache hit rate: 0.0%, External prefix cache hit rate: 0.0%
(APIServer pid=7) INFO 04-10 15:07:18 [loggers.py:259] Engine 000: Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 0 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.0%, Prefix cache hit rate: 0.0%, External prefix cache hit rate: 0.0%
{
    "id": "cmpl-___prefill_addr_host:10.21.9.47,handshake:6301,notify:61005___decode_addr_host:10.21.9.29,handshake:6301,notify:61005_ab377ab0c004415e8a74fbc0e7e1fe62",
    "object": "text_completion",
    "created": 1775833620,
    "model": "deepseek-ai/DeepSeek-R1-0528",
    "choices": [
        {
            "index": 0,
            "text": ".B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42.B\u8bf7\u6c42",
            "logprobs": null,
            "finish_reason": "length",
            "stop_reason": null,
            "token_ids": null,
            "prompt_logprobs": null,
            "prompt_token_ids": null
        }
    ],
    "service_tier": null,
    "system_fingerprint": null,
    "usage": {
        "prompt_tokens": 5,
        "total_tokens": 69,
        "completion_tokens": 64,
        "prompt_tokens_details": null
    },
    "kv_transfer_params": null
}

(Set USE_BENCH=1 for a perf benchmark, or USE_GSM8K=1 for accuracy eval.)

>>> Shutting down containers...
moriio-prefill
moriio-router
Done.
```

---
<details>
<summary> Essential Elements of an Effective PR Description Checklist </summary>

- [X] The purpose of the PR, such as "Fix some issue (link existing issues this PR will resolve)".
- [X] The test plan, such as providing test command.
- [X] The test results, such as pasting the results comparison before and after, or e2e results

### CODE REVIEW

File: src/routers/http/vllm_pd_router.rs [hunk 1]
```diff
@@ -368,18 +426,14 @@ impl VllmPDRouter {
...
         let mut prefill_request = Self::prepare_prefill_request(request_json.clone(), path);
 
-        // Add kv_transfer_params for NixlConnector support at top level
-        // This enables the prefill instance to prepare for remote decode
-        prefill_request["kv_transfer_params"] = json!({
-            "do_remote_decode": true,
-            "do_remote_prefill": false,
-            "remote_engine_id": serde_json::Value::Null,
-            "remote_block_ids": serde_json::Value::Null,
-            "remote_host": serde_json::Value::Null,
```
Comment (simondanielsson) [inline src/routers/http/vllm_pd_router.rs]: remote_host and remote_port are not read by any prefill instance's connector, so it's safe to remove them

**Comment by simon-mo** [comment]
@codex review

File: src/routers/http/vllm_pd_router.rs [hunk 2]
```diff
@@ -140,23 +144,52 @@ impl VllmPDRouter {
         ))
     }
 
+    /// Generate a connector-specific transfer ID for correlating prefill and decode legs.
+    /// Returns `None` for connectors that do not use a transfer_id (e.g. NIXL).
+    fn generate_transfer_id(&self) -> Option<String> {
+        match self.kv_connector {
+            // Mooncake uses the "xfer-<uuid>" format.
+            KvConnector::Mooncake => Some(format!("xfer-{}", Uuid::new_v4())),
+            // MoRI-IO uses the "tx<uuid-no-dashes>" format to match MoRIIOConstants.TRANSFER_PREFIX.
```
Comment (BugenZhao) [inline src/routers/http/vllm_pd_router.rs]:
```suggestion
            // MoRI-IO uses the "tx-<uuid-no-dashes>" format to match MoRIIOConstants.TRANSFER_PREFIX.
```

File: src/routers/http/vllm_pd_router.rs [hunk 3]
```diff
@@ -140,23 +144,52 @@ impl VllmPDRouter {
...
+            KvConnector::MoriIO => Some(format!(
+                "{}-{}",
+                MORIIO_TRANSFER_PREFIX,
+                Uuid::new_v4().to_string().replace('-', "")
```
Comment (BugenZhao) [inline src/routers/http/vllm_pd_router.rs]:
```suggestion
                Uuid::new_v4().simple()
```

**Review by BugenZhao — APPROVED** [review]
Rest LGTM. Thanks!

**Comment by simondanielsson** [comment]
@BugenZhao Does this failing CI look like an unrelated issue to you as well? 🙏

**Comment by BugenZhao** [comment]
> @BugenZhao Does this failing CI look like an unrelated issue to you as well? 🙏 

Yes I think it's #154 aims to resolve.
